version: '3.8'

services:
  # MongoDB configuration
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - doclink-network

  mysql:
    image: mysql:8.0
    container_name: doclink-mysql
    environment:
      MYSQL_DATABASE: dbi481968
      MYSQL_USER: dbi481968
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - doclink-network

  # Backend services
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: doclink-user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbi481968
      SPRING_DATASOURCE_USERNAME: dbi481968
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS: "true"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL-STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    depends_on:
      - mysql
    networks:
      - doclink-network

  post-service:
    build:
      context: ./PostService
      dockerfile: Dockerfile
    container_name: doclink-post-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/postservice
    depends_on:
      - mongodb
    networks:
      - doclink-network

  appointment-service:
    build:
      context: ./AppointmentService
      dockerfile: Dockerfile
    container_name: doclink-appointment-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/appointment-db
    depends_on:
      - mongodb
    networks:
      - doclink-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: doclink-api-gateway
    ports:
      - "9000:9000"
    environment:
      USER_SERVICE_URL: http://user-service:8080
      POST_SERVICE_URL: http://post-service:8081
      APPOINTMENT_SERVICE_URL: http://appointment-service:8082
    depends_on:
      - user-service
      - post-service
      - appointment-service
    networks:
      - doclink-network

  # Frontend
  frontend:
    image: nginx:alpine
    container_name: doclink-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../Fronted/DocLink-FE/dist/doc-link/browser:/usr/share/nginx/html
    depends_on:
      - api-gateway
    networks:
      - doclink-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - doclink-network
    restart: always

    # Grafana for visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - doclink-network
    depends_on:
      - prometheus
    restart: always

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - doclink-network
    volumes:
      - influxdb_data:/var/lib/influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - doclink-network
    command: sleep infinity
    depends_on:
      - influxdb

  test-data-generator:
    build:
      context: ./test-data-generator
      dockerfile: Dockerfile
    container_name: doclink-test-data-generator
    networks:
      - doclink-network
    depends_on:
      - user-service
      - post-service
      - appointment-service

networks:
  doclink-network:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
  prometheus_data:
  grafana_data:
  influxdb_data: