version: '3.8'

services:
  # Monitoring tools
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - doclink-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - doclink-network
    depends_on:
      - prometheus
      - influxdb
    restart: always

  # Load testing tools
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - doclink-network
    volumes:
      - influxdb_data:/var/lib/influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - doclink-network
    command: sleep infinity
    depends_on:
      - influxdb

  test-data-generator:
    build:
      context: ./test-data-generator
      dockerfile: Dockerfile
    container_name: doclink-test-data-generator
    networks:
      - doclink-network
    depends_on:
      - influxdb

networks:
  doclink-network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  influxdb_data: