apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: doclink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: doclink/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:8080"
            - name: POST_SERVICE_URL
              value: "http://post-service:8081"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:8082"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: doclink
spec:
  selector:
    app: api-gateway
  ports:
    - port: 9000
      targetPort: 9000
  type: NodePort