apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: doclink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: doclink/appointment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-service:27017/appointment-db"
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: doclink
spec:
  selector:
    app: appointment-service
  ports:
    - port: 8082
      targetPort: 8082