apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: doclink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: "ghcr-secret"
      containers:
        - name: frontend
          image: ghcr.io/ovidiucarlan/doclink-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: doclink
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer