apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: doclink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: doclink/post-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-service:27017/postservice"
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: doclink
spec:
  selector:
    app: post-service
  ports:
    - port: 8081
      targetPort: 8081