apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: doclink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: "ghcr-secret"
      containers:
        - name: user-service
          image: ghcr.io/ovidiucarlan/doclink-userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/dbi481968"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbi481968"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: doclink
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
